---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/nluzgin/db_config
    owner: nluzgin
    group: nluzgin
  notify: reload puma

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: enable puma
  systemd: name=puma enabled=yes

# Иначе ругается при установке (заметил совсем недавно)
- name: Upgrade bundler package to the latest version
  apt:
    name: "bundler"
    state: latest
